services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  KimaiPlugin\UiImprovementsBundle\:
    resource: '../../*'
    exclude:
      - '../../Resources/'
      - '../../Exception/'

  KimaiPlugin\UiImprovementsBundle\Controller\:
    resource: '../../Controller'
    tags: [ 'controller.service_arguments' ]
